blank_issues_enabled: false
contact_links:
  - name: "버그 리포트"
    url: "/issues/new?template=bug_template.yml"
    about: "버그 발생 시 제보해주세요."
  - name: "기능 요청"
    url: "/issues/new?template=feature_template.yml"
    about: "새로운 기능을 요청해주세요."
  - name: "기타 건의 사항"
    url: "/issues/new?template=etc_template.yml"
    about: "기타 건의 사항을 제안해주세요."
